---
version: '3.1'

services: 
  mariadb:
    container_name: mariadb
    image: mariadb:10.9.3-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: juve

  webapp:
    container_name: webappp
    image: fyligrane/exo3:1.0.0
    build:
      context: .
    ports: 
    - 32703:5000
    depends_on:
    - mariadb
    restart: always