---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
  namespace: exo3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: exo3

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: fyligrane/exo3:1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "1m"
          limits:
            memory: "128Mi"
            cpu: "2m"
---
apiVersion: v1 
kind: Service
metadata:
  name: webapp-service
  namespace: exo3

spec:
  type: NodePort
  selector:  
    app: webapp
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32703
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-scaler
  namespace: exo3

spec:
  scaleTargetRef:
    kind: Deployment
    name: webapp-deploy
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1 
kind: Pod
metadata:
  name: mariadb-pod
  namespace: exo3
  labels: 
    db: mariadb

spec:
  volumes:
  - name: mariadb-vol
    persistentVolumeClaim:
      claimName: mariadb-pvc
  - name: initdb-vol
    configMap:
      name: initdb-configmap
  containers:
  - name: mariadb-container
    image: mariadb:10.9.3-jammy
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: juve
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    volumeMounts:
    - name: mariadb-vol
      mountPath: /var/lib/mysql
    - name: initdb-vol
      mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1 
kind: Service
metadata:
  name: mariadb
  namespace: exo3

spec:
  type: ClusterIP
  selector:  
    db: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP